"""tracking sessions

Revision ID: 1e2865afd83e
Revises: 840970569344
Create Date: 2026-10-08 21:09:07.235856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2865afd83e'
down_revision = '840970569344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('corper_name', sa.String(length=120), nullable=False),
    sa.Column('from_label', sa.String(length=120), nullable=False),
    sa.Column('to_label', sa.String(length=120), nullable=False),
    sa.Column('operator', sa.String(length=120), nullable=False),
    sa.Column('vehicle', sa.String(length=120), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_location_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracking_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_tracking_sessions_token'))

    op.drop_table('tracking_sessions')
    # ### end Alembic commands ###
